# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[(b'PENDING', '\u8349\u7a3f'), (b'ACTIVE', '\u8fdb\u884c\u4e2d'), (b'DONE', '\u5b8c\u6210')], max_length=20),
        ),
    ]
