# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20170211_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paymentterm',
            field=models.CharField(default='\u6b3e\u5230\u53d1\u8d27', max_length=100),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='paymentterm',
            field=models.CharField(default='\u6b3e\u5230\u53d1\u8d27', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'PENDING', '\u8349\u7a3f'), (b'ACTIVE', '\u8fdb\u884c\u4e2d'), (b'DONE', '\u5b8c\u6210')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderaccount',
            name='account',
            field=models.CharField(choices=[(b'CON_US', '\u5efa\u884c-\u7f8e\u91d1'), (b'CON_RMB', '\u5efa\u884c-\u4eba\u6c11\u5e01'), (b'WESTUNION', '\u897f\u8054'), (b'ALIBABA_US', '\u963f\u91cc\u5df4\u5df4-\u7f8e\u91d1'), (b'ALIBABA_RMB', '\u963f\u91cc\u5df4\u5df4-\u4eba\u6c11\u5e01'), (b'PAYPAL1', '\u8d1d\u5b9d-lianhuness@gmail.com'), (b'PAYPAL2', '\u8d1d\u5b9d-yiqizhu@hongdalatex.com'), (b'ZENRONGMEI', '\u66fe-\u519c\u884c')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderaccount',
            name='currency',
            field=models.CharField(choices=[(b'USD', '\u7f8e\u91d1'), (b'RMB', '\u4eba\u6c11\u5e01')], default=b'RMB', max_length=10),
        ),
    ]
