# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20170211_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderaccount',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='orderaccount',
            name='currency',
        ),
    ]
