# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20170212_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packing',
            field=models.TextField(blank=True),
        ),
    ]
