# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_order_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'PENDING', '\u8349\u7a3f'), (b'SUBMIT', '\u63d0\u4ea4'), (b'DONE', '\u53d1\u8d27')], default=b'PENDING', max_length=20),
        ),
    ]
