# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ranking',
            field=models.CharField(choices=[(b'A', '\u5f00\u53d1\u9636\u6bb5'), (b'B', '\u6b63\u5e38\u64cd\u4f5c\u9636\u6bb5'), (b'C', '\u91cd\u70b9\u5ba2\u6237')], default='', max_length=10),
        ),
    ]
